default:
  SENTRY_DSN: 'https://8abfa36904a248f69388ea570014a592@sentry.io/1315098'
  MONGO_DB_NAME: 'spiderNest'
  IMAGE_COLLECTION: 'images'

development:
  MONGO_URI: 'mongodb://127.0.0.1:27017'

testing:
  MONGO_DB_NAME: 'spiderNest-test'
  MONGO_URI: 'mongodb://127.0.0.1:27017'